language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
  - "pypy"
  - "pypy3"
# command to run tests
install: python setup.py develop
# Nothing needed
script: python setup.py test

